# Generated by Django 6.0.5 on 2026-08-22 09:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('language_pref', models.CharField(default='en', max_length=10)),
                ('is_admin', models.BooleanField(default=False, help_text='Gates the analytics dashboard and administrative features.')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(blank=True, max_length=100, null=True)),
                ('cost_index', models.DecimalField(blank=True, decimal_places=2, help_text='Relative cost-of-living index for budgeting.', max_digits=6, null=True)),
                ('popularity', models.IntegerField(default=0, help_text='Drives recommended destinations.')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
                'db_table': 'cities',
                'ordering': ['-popularity', 'name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'country'), name='unique_city_country')],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[('sightseeing', 'Sightseeing'), ('food', 'Food & Dining'), ('adventure', 'Adventure & Outdoors'), ('culture', 'Culture & History'), ('nightlife', 'Nightlife'), ('shopping', 'Shopping'), ('relaxation', 'Relaxation & Wellness'), ('other', 'Other')], max_length=50, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.city')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'db_table': 'activities',
                'ordering': ['city', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('trip_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('budget_limit', models.DecimalField(blank=True, decimal_places=2, help_text="User's planned maximum budget.", max_digits=12, null=True)),
                ('cover_photo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='Enables the shareable public view.')),
                ('public_slug', models.SlugField(blank=True, help_text='Used in the public share URL.', max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Trip',
                'verbose_name_plural': 'Trips',
                'db_table': 'trips',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TripCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copied_at', models.DateTimeField(auto_now_add=True)),
                ('copied_by_user', models.ForeignKey(db_column='copied_by_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='trip_copies', to=settings.AUTH_USER_MODEL)),
                ('copied_trip', models.ForeignKey(db_column='copied_trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='copy_lineage', to='api.trip')),
                ('original_trip', models.ForeignKey(db_column='original_trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='copies_originated', to='api.trip')),
            ],
            options={
                'verbose_name': 'Trip Copy',
                'verbose_name_plural': 'Trip Copies',
                'db_table': 'trip_copies',
                'ordering': ['-copied_at'],
            },
        ),
        migrations.CreateModel(
            name='TripShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'View'), ('edit', 'Edit')], default='view', max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('shared_with_user', models.ForeignKey(db_column='shared_with_user_id', on_delete=django.db.models.deletion.CASCADE, related_name='shared_trips', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='api.trip')),
            ],
            options={
                'verbose_name': 'Trip Share',
                'verbose_name_plural': 'Trip Shares',
                'db_table': 'trip_shares',
                'ordering': ['-shared_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('sequence_order', models.PositiveIntegerField(help_text='Supports drag-to-reorder.')),
                ('arrival_date', models.DateField()),
                ('departure_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='trip_stops', to='api.city')),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='api.trip')),
            ],
            options={
                'verbose_name': 'Trip Stop',
                'verbose_name_plural': 'Trip Stops',
                'db_table': 'trip_stops',
                'ordering': ['trip', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='TripActivity',
            fields=[
                ('trip_activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('scheduled_date', models.DateField(help_text="Must fall within the stop's date range.")),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('cost_override', models.DecimalField(blank=True, decimal_places=2, help_text='User-edited cost, if different from default.', max_digits=10, null=True)),
                ('sequence_order', models.PositiveIntegerField(default=1, help_text='Order within the day.')),
                ('activity', models.ForeignKey(db_column='activity_id', on_delete=django.db.models.deletion.CASCADE, related_name='trip_activities', to='api.activity')),
                ('stop', models.ForeignKey(db_column='stop_id', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='api.tripstop')),
            ],
            options={
                'verbose_name': 'Trip Activity',
                'verbose_name_plural': 'Trip Activities',
                'db_table': 'trip_activities',
                'ordering': ['scheduled_date', 'sequence_order', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('budget_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('stay', 'Stay / Accommodation'), ('activities', 'Activities'), ('meals', 'Meals & Dining'), ('other', 'Other')], max_length=50)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('expense_date', models.DateField(blank=True, null=True)),
                ('trip', models.ForeignKey(db_column='trip_id', on_delete=django.db.models.deletion.CASCADE, related_name='budget_items', to='api.trip')),
                ('stop', models.ForeignKey(blank=True, db_column='stop_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='budget_items', to='api.tripstop')),
            ],
            options={
                'verbose_name': 'Budget Item',
                'verbose_name_plural': 'Budget Items',
                'db_table': 'budget_items',
                'ordering': ['-expense_date', '-budget_item_id'],
            },
        ),
        migrations.CreateModel(
            name='SavedDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(db_column='city_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_users', to='api.city')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='saved_destinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Destination',
                'verbose_name_plural': 'Saved Destinations',
                'db_table': 'saved_destinations',
                'ordering': ['-saved_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'city'), name='unique_user_saved_city')],
            },
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='check_trip_end_date_gte_start_date'),
        ),
        migrations.AddConstraint(
            model_name='tripcopy',
            constraint=models.UniqueConstraint(fields=('original_trip', 'copied_trip'), name='unique_trip_copy'),
        ),
        migrations.AddConstraint(
            model_name='tripshare',
            constraint=models.UniqueConstraint(fields=('trip', 'shared_with_user'), name='unique_trip_share'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.CheckConstraint(condition=models.Q(('departure_date__gte', models.F('arrival_date'))), name='check_stop_departure_gte_arrival'),
        ),
        migrations.AddConstraint(
            model_name='tripstop',
            constraint=models.UniqueConstraint(fields=('trip', 'sequence_order'), name='unique_trip_sequence_order'),
        ),
        migrations.AddConstraint(
            model_name='tripactivity',
            constraint=models.UniqueConstraint(fields=('stop', 'scheduled_date', 'sequence_order'), name='unique_stop_date_sequence_order'),
        ),
    ]
