# Generated by Django 6.0.7 on 2026-08-22 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activity",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="image_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="trip",
            name="cover_photo_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
